# Generated by Django 4.2.4 on 2023-12-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zapatillas',
            new_name='ProductoStock',
        ),
    ]
