# Generated by Django 4.2.4 on 2023-12-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apitest', '0002_rename_zapatillas_productostock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productostock',
            options={'permissions': [('puede_eliminar_producto', 'Puede eliminar productos'), ('puede_actualizar_producto', 'Puede actualizar productos')]},
        ),
    ]
