# Generated by Django 4.2.4 on 2023-12-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apitest', '0003_alter_productostock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productostock',
            options={},
        ),
        migrations.AlterModelTable(
            name='productostock',
            table='apitest_productostock',
        ),
    ]
