# Generated by Django 4.2.4 on 2023-12-06 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productostock',
            options={'permissions': [('puede_eliminar_producto', 'Puede eliminar productos'), ('puede_actualizar_producto', 'Puede actualizar productos')]},
        ),
        migrations.AlterField(
            model_name='productostock',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
