# Generated by Django 4.2.4 on 2023-12-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_alter_productostock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productostock',
            table='stock_productostock',
        ),
    ]
