# Generated by Django 4.2.4 on 2023-12-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_alter_productostock_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productostock',
            table=None,
        ),
    ]
